#==================== Tomcat Setting =====================#
server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8

file-service:
  token: 1234567890Yeager
  save:
    path: D:\test\
  file-type:
    picture: jpg,png,bmp,gif,jpeg,psd,svg
    doc: doc,docx,xls,xlsx,txt
    video: rmvb,mkv,mp4,avi,3gp,amv,dmv,rm,mpeg,wmv
    audio: mp3,wma,wav,ogg
  service-name: system-service,ifox-web
  admin-user-service-base-url: http://localhost:8081/

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    static-path-pattern: /**
  http.multipart:
      max-request-size: 30MB
      max-file-size: 30MB