#==================== Tomcat Setting =====================#
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

#==================== sessionFactory Setting =====================#
sessionFactory:
  package.scan: com.ifox.platform.entity

#==================== spring Setting =====================#
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    static-path-pattern: /**
  http.multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  jpa:
    generate-ddl:
      true
    hibernate:
      ddl-auto:
        update
      naming.implicit-strategy:
        org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      naming.physical-strategy:
        org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  aop:
    proxy-target-class: true

#==================== logging Setting =====================#
logging:
  level:
    org.springframework: info
    org.hibernate: info
    com.ifox.platform: debug
  file: logs/system-service.log

#==================== DataSource Setting =====================#
# https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
# 通常只需要更改以下三个配置 initialSize:初始化连接数量, minIdle:最小连接池数量, maxIdle:已经不再使用，配置了也没效果, maxActive:最大连接池数量
app.datasource:
  jdbc:
    url: jdbc:mysql://localhost:3306/pure_site?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Aswd1234
    driver: com.mysql.jdbc.Driver
  pool:
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat


#==================== Hibernate Configuration =====================#
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl.auto: update
  generate_statistics: false
  max_fetch_depth: 1
  jdbc:
    fetch_size: 30
    batch_size: 30
  cache:
    use_second_level_cache: true
    use_query_cache: false
    provider_class: org.hibernate.cache.NoCacheProvider

#==================== JWT Configuration =====================#
jwt:
  secret: 123456
  payload:
    iss: www.yeager.vip
    exp: 100
