#==================== Tomcat Setting =====================#
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

#==================== spring Setting =====================#
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    static-path-pattern: /**
  http.multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Aswd1234
    url: jdbc:mysql://localhost:3306/spring_data_test
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false

#==================== logging Setting =====================#
logging:
  level:
    org.springframework: info
    org.hibernate: info
    com.ifox.platform: debug
  file: logs/system-service.log

#==================== JWT Configuration =====================#
jwt:
  secret: 123456
  payload:
    iss: www.yeager.vip
    exp: 100
